export const BOOKED_CREATE_REQUEST = 'BOOKED_CREATE_REQUEST'
export const BOOKED_CREATE_SUCCESS = 'BOOKED_CREATE_SUCCESS'
export const BOOKED_CREATE_FAIL = 'BOOKED_CREATE_FAIL'




export const BOOKED_DETAILS_REQUEST = 'BOOKED_DETAILS_REQUEST'
export const BOOKED_DETAILS_SUCCESS = 'BOOKED_DETAILS_SUCCESS'
export const BOOKED_DETAILS_FAIL = 'BOOKED_DETAILS_FAIL'



export const BOOKED_PAY_REQUEST = 'BOOKED_PAY_REQUEST'
export const BOOKED_PAY_SUCCESS = 'BOOKED_PAY_SUCCESS'
export const BOOKED_PAY_FAIL = 'BOOKED_PAY_FAIL'
export const BOOKED_PAY_RESET = 'BOOKED_PAY_RESET'



export const BOOKED_LIST_MY_REQUEST = 'BOOKED_LIST_MY_REQUEST'
export const BOOKED_LIST_MY_SUCCESS = 'BOOKED_LIST_MY_SUCCESS'
export const BOOKED_LIST_MY_FAIL = 'BOOKED_LIST_MY_FAIL'
export const BOOKED_LIST_MY_RESET = 'BOOKED_LIST_MY_RESET'

//ALL ORDER SHOW

export const BOOKED_LIST_REQUEST = 'BOOKED_LIST_REQUEST'
export const BOOKED_LIST_SUCCESS = 'BOOKED_LIST_SUCCESS'
export const BOOKED_LIST_FAIL = 'BOOKED_LIST_FAIL'



//DELIVERED

export const BOOKED_DELIVER_REQUEST = 'BOOKED_DELIVER_REQUEST'
export const BOOKED_DELIVER_SUCCESS = 'BOOKED_DELIVER_SUCCESS'
export const BOOKED_DELIVER_FAIL = 'BOOKED_DELIVER_FAIL'
export const BOOKED_DELIVER_RESET = 'BOOKED_DELIVER_RESET'