export const BOOKING_ADD_ITEM = 'BOOKING_ADD_ITEM'
export const BOOKING_REMOVE_ITEM = 'BOOKING_REMOVE_ITEM'
export const BOOKING_SAVE_PROCESS_ADDRESS = 'BOOKING_SAVE_PROCESS_ADDRESS'
export const BOOKING_SAVE_PAYMENT_METHOD = 'BOOKING_SAVE_PAYMENT_METHOD'